In [7]:
import pandas as pd

In [10]:
data=pd.read_csv("indian_roads_dataset.csv")

In [11]:
data.head()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10

In [13]:
data.shape

(20000, 24)

In [14]:
data.isnull().sum()

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

In [16]:
data.duplicated().sum()

np.int64(0)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  object
 6   time               20000 non-null  object
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           115 non-null    object
 23  risk_score         20000 non-null  float64
dtypes: float64(3), int64(9), object(12)
memory usage: 3.7+ MB

In [21]:
# to check unique values
data.nunique()

accident_id          20000
city                     8
state                    7
latitude             19907
longitude            19927
date                  1201
time                    24
hour                    24
day_of_week              7
is_weekend               2
road_type                3
lanes                    6
traffic_signal           2
weather                  3
visibility               3
temperature             26
traffic_density          3
cause                    5
accident_severity        3
vehicles_involved        5
casualties               6
is_peak_hour             2
festival                 4
risk_score              18
dtype: int64

In [22]:
data.describe()

,accident_id,latitude,longitude,hour,is_weekend,lanes,traffic_signal,temperature,vehicles_involved,casualties,is_peak_hour,risk_score
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,9999.500000,20.389207,78.173330,11.487200,0.286150,3.493950,0.499850,27.579600,2.992000,1.726450,0.247400,0.437585
std,5773.647028,6.165791,4.485967,6.945563,0.451972,1.705406,0.500012,7.454746,1.415534,1.489104,0.431512,0.218130
min,0.000000,12.800172,72.700017,0.000000,0.000000,1.000000,0.000000,15.000000,1.000000,0.000000,0.000000,0.100000
25%,4999.750000,13.198653,73.997979,5.000000,0.000000,2.000000,0.000000,21.000000,2.000000,1.000000,0.000000,0.250000
50%,9999.500000,18.812008,77.297000,12.000000,0.000000,4.000000,0.000000,28.000000,3.000000,1.000000,0.000000,0.450000
75%,14999.250000,28.402467,80.111089,18.000000,1.000000,5.000000,1.000000,34.000000,4.000000,3.000000,0.000000,0.600000
max,19999.000000,30.799960,88.499861,23.000000,1.000000,6.000000,1.000000,40.000000,5.000000,5.000000,1.000000,1.000000

In [24]:
data['festival'].value_counts(dropna=False)

festival
NaN         19885
Holi           38
Eid            34
Diwali         31
New Year       12
Name: count, dtype: int64

In [25]:
# replacing na with no festival 
data['festival']=data['festival'].fillna('No festival')

In [26]:
data['festival'].value_counts(dropna=False)

festival
No festival    19885
Holi              38
Eid               34
Diwali            31
New Year          12
Name: count, dtype: int64

In [31]:
data['festival_flag'] = data['festival'].apply(
    lambda x: 0 if x == 'No festival' else 1
)

In [32]:
data.head()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score,festival_flag
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,32,high,weather,fatal,2,2,0,No festival,0.85,0
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,34,low,weather,major,4,3,0,No festival,0.10,0
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,21,medium,weather,minor,1,1,0,No festival,0.45,0
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,30,high,distraction,minor,5,2,0,No festival,0.65,0
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,24,low,distraction,minor,2,1,0,No festival,0.10,0

In [36]:
data.to_csv("cleaned_indian_roads_dataset.csv", index=False)